name: github pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build

    #发布到 gcdxuzhiwei.github.io/main
    - name: Deploy gcdxuzhiwei.github.io/main
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: gcdxuzhiwei/gcdxuzhiwei.github.io #可以新建一个gcdxuzhiwei.github.io仓库发布到main
        PUBLISH_BRANCH: main
        PUBLISH_DIR: docs/.vuepress/dist
      with:
          emptyCommits: false
